:ems:
  :ems_scvmm:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
:ems_refresh:
  :scvmm:
    :refresh_interval: 15.minutes
:http_proxy:
  :scvmm:
    :host:
    :password:
    :port:
    :user:
:log:
  :level_scvmm: info
:workers:
  :ems_refresh_worker_microsoft:
    :inherits_from: ems_refresh_worker
